version: "3.7"

services:
  server:
    image: iskorotkov/chaos-server:latest
    command: ["-port", "8811"]
    hostname: server
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
    networks:
      - private

  writer:
    image: iskorotkov/chaos-client:latest
    depends_on:
      - server
      - muxy
    networks:
      - public
    deploy:
      replicas: 3
      restart_policy:
        delay: 5s
        max_attempts: 5
    command: ["-host", "muxy", "-port", "18811", "-verb", "post", "-rate", "1"]

  reader:
    image: iskorotkov/chaos-client:latest
    depends_on:
      - server
      - muxy
    networks:
      - public
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
    command: ["-host", "muxy", "-port", "18811", "-verb", "get", "-rate", "1"]

  muxy:
    image: mefellows/muxy:v0.0.5
    hostname: muxy
    privileged: true
    volumes:
      - ./../config:/opt/muxy/conf/:ro
    networks:
      - public
      - private

networks:
  public:
    driver: overlay
  private:
    driver: overlay
