name: Network and HTTP screwer.
description: Slow network to mobile levels, and add 1s delay to all messages
loglevel: 0

proxy:
  - name: http_proxy
    config:
      host: 0.0.0.0
      port: 18811
      protocol: http
      proxy_host: server
      proxy_port: 8811
      proxy_protocol: http

middleware:
  - name: logger
    config:
      hex_output: false

#  - name: delay
#    config:
#      request_delay: 1000
#      response_delay: 500
#
#  - name: http_tamperer
#    config:
#      response:
#        status: 500
#
#  - name: tcp_tamperer
#    config:
#      request:
#        body: "wow, new request!"
#        randomize: true
#        truncate: true
#      response:
#        body: "wow, new response!"
#        randomize: true
#        truncate: true

#  - name: network_shape
#    config:
#      latency: 250
#      target_bw: 750
#      default_bw: 750
#      packet_loss: 20
#      target_ips:
#        - "0.0.0.0/0"
#      target_ips6:
#        - "::1/128"
#      target_ports:
#        - "18811"
#      target_protos:
#        - "tcp"
#        - "udp"
#        - "icmp"
#      device: eth0
